services:
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk # Pre-generated UUID for KRaft mode. In production, we would normally generate this dynamically.

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka-data:/var/lib/kafka/data

  ingestion-service:
    build:
      context: ./ingestion-service
    container_name: ingestion-service
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      SERVICE_NAME: ingestion-service
      HTTP_PORT: 8080
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: charger.telemetry.raw
    restart: unless-stopped
  
  consumer-service:
    build:
      context: ./consumer-service
    container_name: consumer-service
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
      KAFKA_TOPIC: charger.telemetry.raw
      KAFKA_GROUP_ID: charger-consumers
      DATABASE_URL: postgres://telemetry:telemetry@timescaledb:5432/telemetry

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      POSTGRES_USER: telemetry
      POSTGRES_PASSWORD: telemetry # use proper secret management in any real scenario (production or development). Only plain text for simplicity of this challenge.
      POSTGRES_DB: telemetry
    ports:
      - "5432:5432"
    volumes:
      - tsdb-data:/var/lib/postgresql/data
      - ./timescaledb/init:/docker-entrypoint-initdb.d


volumes:
  kafka-data:
  tsdb-data:
